# Generated by Django 4.2.3 on 2023-08-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientmodel",
            name="spent_money",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
