version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10

  db:
    image: postgres:15.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
